name: Test to bundle release artifacts

on: [workflow_dispatch]

jobs:
    build:
        strategy:
            matrix:
                settings:
                    - host: macos-latest
                      target: macos
                    - host: windows-latest
                      target: win
                      extension: .exe
                    - host: ubuntu-latest
                      target: linux
        runs-on: ${{ matrix.settings.host }}
        name: dev build - ${{ matrix.settings.target }} - node@18
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - run: yarn
            - run: yarn run build
            # remove dev dependencies before packaging
            - run: yarn workspaces focus --all --production
            # package final binaries
            - run: |
                  yarn dlx pkg . -t node18-${{ matrix.settings.target }}-x64 -o bundle/dcli-${{ matrix.settings.target }}-x64${{ matrix.settings.extension }} -C GZip "--public" "--public-packages" "tslib,thirty-two" "--no-bytecode"
                  yarn dlx pkg . -t node18-${{ matrix.settings.target }}-arm64 -o bundle/dcli-${{ matrix.settings.target }}-arm64${{ matrix.settings.extension }} -C GZip "--public" "--public-packages" "tslib,thirty-two" "--no-bytecode"

            - name: Archive binary artifact
              uses: actions/upload-artifact@v3
              with:
                  name: dcli-${{ matrix.settings.target }}
                  path: |
                      bundle/dcli-${{ matrix.settings.target }}-x64${{ matrix.settings.extension }}
                      bundle/dcli-${{ matrix.settings.target }}-arm64${{ matrix.settings.extension }}
                  retention-days: 1

    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - name: Download all artifacts
              uses: actions/download-artifact@v3
              with:
                  path: artifacts

            - name: List artifacts
              run: ls -R artifacts
              shell: bash
